AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  example:
    Type: String

Resources:
  functionAdd:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: src/add/
      AutoPublishAlias: addAlias
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute
      Events:
        Add:
          Type: Api
          Properties:
            Path: !Sub
              - ${env}/add
            Method: GET
  functionSubtract:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: src/subtract/
      AutoPublishAlias: subtractAlias
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute
      Events:
        Add:
          Type: Api
          Properties:
            Path: !Sub
              - ${env}/subtract
            Method: GET